Updates
Signed-off-by: Christopher Larson <kergoth@gmail.com>

diff --git a/scripts/github-mirror b/scripts/github-mirror
--- a/scripts/github-mirror
+++ b/scripts/github-mirror
@@ -42,15 +42,17 @@ if [ -e "$dest/.done" ] && [ -z "$update" ]; then
     exit 0
 fi
 
-if [ "$base" != "$repo_name" ]; then
-    echo >&2 "Error: base $base != $repo_name, might need to refetch and rsync"
-    exit 1
-fi
+# if [ "$base" != "$repo_name" ]; then
+#     echo >&2 "Error: base $base != $repo_name, might need to refetch and rsync"
+#     exit 1
+# fi
 
 if command -v git-lfs >/dev/null 2>&1; then
     set -- --lfs "$@"
 fi
 ln -s "$repodir" "$tmpdir/repositories"
+
+set -x
 
 github-backup ${GITHUB_TOKEN:+-t "$GITHUB_TOKEN"} --all --pull-details ${ARGS:+$ARGS} -R "$repo_name" -o "$tmpdir" "$user" || :
 github-backup ${GITHUB_TOKEN:+-t "$GITHUB_TOKEN"} --releases --assets ${ARGS:+$ARGS} -R "$repo_name" -o "$tmpdir" "$user" || :
diff --git a/scripts/sf-download b/scripts/sf-download
--- a/scripts/sf-download
+++ b/scripts/sf-download
@@ -29,6 +29,8 @@ usage() {
 main () {
     process_arguments "$@"
     shift $((OPTIND - 1))
+    echo wayback: $wayback
+    echo args: "$@"
 
     tmpdir=$(mktemp -d -t "${0##*/}.XXXXXX")
     trap 'rm -rf "$tmpdir"' EXIT INT TERM
@@ -195,7 +197,7 @@ run_commands () {
             printf '%s\n' "$cmd"
         else
             # shellcheck disable=SC2059
-            printf "( $fmt )"' || { echo >&2 "Error fetching"; exit 1; }\n' "$cmd" 
+            printf "( $fmt )"' || { echo >&2 "Error fetching"; exit 1; }\n' "$cmd"
         fi
     done | \
     tr '\n' '\0' | \
